---
    version: "2.1"
    services:
      bazarr:
        image: ghcr.io/linuxserver/bazarr
        container_name: bazarr
        environment:
          - PUID=1026
          - PGID=100
          - TZ=Europe/Zurich
        volumes:
          - /volume1/docker/bazarr:/config # config
          - /volume1/plex-library/movies:/movies 
          - /volume1/plex-library/tv:/tv 
          - /volume1/plex-library/anime:/anime 
        ports:
          - 6767:6767
        restart: unless-stopped