---
    version: "2.1"
    services:
      tautulli:
        image: ghcr.io/linuxserver/tautulli
        container_name: tautulli
        environment:
          - PUID=1026 
          - PGID=100 
          - TZ=Europe/Zurich
        volumes:
          - /volume1/docker/tautulli:/config
        ports:
          - 8181:8181
        restart: unless-stopped