---
    version: "2.1"
    services:
      nzbhydra2:
        image: ghcr.io/linuxserver/nzbhydra2
        container_name: nzbhydra2
        environment:
          - PUID=1026
          - PGID=100
          - TZ=Europe/Zurich
        volumes:
          - /volume1/docker/nzbhydra:/config
          - /volume1/Downloads/usenet/nzb-blackhole:/blackholes/nzb
          - /volume1/Downloads/torrent/torrent-blackhole:/blackholes/torrent
        ports:
          - 5076:5076
        restart: unless-stopped